# Generated by Django 2.2.24 on 2022-02-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220217_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='customer',
        ),
    ]
